services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cs_os_ms'
      - 'POSTGRES_PASSWORD=training'
      - 'POSTGRES_USER=cs_os_ms'
    ports:
      - "5432:5432"
